import { categories } from '../data/categories.js';

export function AdminPanel() {
  return `<div class="admin-panel-overlay" id="adminPanelOverlay" role="dialog" aria-modal="true" aria-labelledby="adminPanelTitle">
    <div class="admin-panel">
      <div class="admin-panel-header">
        <h2 id="adminPanelTitle"><i class="fas fa-gem icon-gap-8 icon-font-poppins"></i> Editor de Precios</h2>
        <div class="admin-header-actions"><button class="admin-device-btn" id="adminLogoutBtn" type="button"><i class="fas fa-sign-out-alt"></i> Desautorizar dispositivo</button><button class="admin-close-btn" id="adminCloseBtn" type="button"><i class="fas fa-times icon-gap-6"></i>Cerrar</button></div>
      </div>
      <section class="admin-device-section" aria-labelledby="deviceSectionTitle">
        <div class="admin-device-section-heading"><div><h3 id="deviceSectionTitle">Dispositivos autorizados</h3><p>Autoriza otros celulares o computadores con un enlace de un solo uso.</p></div><button class="admin-device-btn" id="adminCreateInviteBtn" type="button"><i class="fas fa-link"></i> Crear enlace</button></div>
        <div class="admin-invite-form" id="adminInviteForm" hidden><label for="adminInviteLabel">Nombre del dispositivo</label><div class="admin-invite-row"><input id="adminInviteLabel" type="text" maxlength="80" placeholder="Ej: Celular de Mateo"><button class="admin-save-btn" id="adminConfirmInviteBtn" type="button">Generar</button></div></div>
        <div class="admin-invite-result" id="adminInviteResult" role="status" aria-live="polite"></div><div class="admin-devices-list" id="adminDevicesList"><span class="admin-muted">Cargando dispositivos…</span></div>
      </section>
      <div class="admin-cat-tabs" id="adminCatTabs"><button class="admin-cat-tab active" data-cat="all">Todos</button>${categories.map((category) => `<button class="admin-cat-tab" data-cat="${category.id}">${category.adminLabel}</button>`).join('')}</div>
      <div class="admin-bulk"><label for="adminBulkMultiplier">Multiplicar productos de la categoría activa por:</label><input type="number" id="adminBulkMultiplier" value="2" step="0.5" min="0.5" max="100"><button class="admin-bulk-btn" onclick="adminBulkMultiply()">Aplicar ×<span id="adminBulkDisplay">2</span></button><button class="admin-bulk-btn admin-reset-btn" onclick="adminResetPrices()"><i class="fas fa-rotate-left icon-gap-4"></i>Restaurar</button></div>
      <div class="admin-search"><div class="admin-search-wrap"><i class="fas fa-search"></i><input type="text" id="adminSearchInput" placeholder="Buscar producto..." autocomplete="off"></div></div>
      <div class="admin-add-section"><button class="admin-add-toggle" id="adminAddProductToggle" type="button"><i class="fas fa-plus-circle"></i> Agregar Producto Nuevo</button><div class="admin-add-form" id="adminAddProductForm"><div class="admin-add-row"><div class="admin-add-field"><label for="newProductName">Nombre del Producto</label><input type="text" id="newProductName" placeholder="Ej: Labial Mate Rojo"></div><div class="admin-add-field"><label for="newProductBrand">Marca</label><input type="text" id="newProductBrand" placeholder="Ej: Maybelline"></div></div><div class="admin-add-row"><div class="admin-add-field"><label for="newProductPrice">Precio (COP)</label><input type="number" id="newProductPrice" placeholder="Ej: 15000" min="0" step="100"></div><div class="admin-add-field"><label for="newProductCategory">Categoría</label><select id="newProductCategory">${categories.map((category) => `<option value="${category.id}">${category.adminLabel}</option>`).join('')}</select></div></div><div class="admin-add-row"><div class="admin-add-field"><label for="newProductImg">URL de Imagen</label><input type="url" id="newProductImg" placeholder="https://..."><img class="img-preview" id="newProductImgPreview" alt="Vista previa"></div></div><button class="admin-add-submit" id="adminAddProductBtn" type="button"><i class="fas fa-plus icon-gap-6"></i>Agregar al Catálogo</button></div></div>
      <div class="admin-add-section"><button class="admin-add-toggle" id="adminAddCategoryToggle" type="button"><i class="fas fa-plus-circle"></i> Agregar Categoría Nueva</button><div class="admin-add-form" id="adminAddCategoryForm"><div class="admin-cat-add-row"><div class="admin-add-field"><label for="newCatId">ID (sin espacios)</label><input type="text" id="newCatId" placeholder="Ej: skincare"></div><div class="admin-add-field"><label for="newCatName">Nombre</label><input type="text" id="newCatName" placeholder="Ej: Cuidado Facial"></div><div class="admin-add-field"><label for="newCatIcon">Icono (Font Awesome)</label><input type="text" id="newCatIcon" placeholder="Ej: fa-spa" value="fa-star"></div><div class="admin-add-field"><label for="newCatSubtitle">Subtítulo Banner</label><input type="text" id="newCatSubtitle" placeholder="Ej: Tu rutina de belleza"></div></div><button class="admin-cat-add-btn" id="adminAddCategoryBtn" type="button"><i class="fas fa-folder-plus icon-gap-5"></i>Crear Categoría</button></div></div>
      <div class="admin-counter" id="adminCounter">0 productos</div><div id="adminProductList"></div><div class="admin-bottom-bar"><button class="admin-save-btn" onclick="adminSavePrices()"><i class="fas fa-check icon-gap-8"></i>Guardar Cambios</button><button class="admin-download-btn" onclick="adminDownloadHTML()"><i class="fas fa-download icon-gap-6"></i>Exportar datos</button></div>
    </div>
  </div><div class="admin-toast" id="adminToast"></div>`;
}
